build:
  stage: build
  before_script:
    - source /cvmfs/cepcsw.ihep.ac.cn/prototype/setup.sh
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build/


